# Site Definition
title: duclvz's Blog
name: duclvz
description: duclvz's blog
email: duclvzz@gmail.com
baseurl: ""
url: "https://duclvz.github.io"
logo: /assets/images/logo.png
icon: /assets/images/icon.png
cdn: ""

ampdir: amp
netlify_cms: false

permalink: /:categories/:title/

collections:
  english:
    output: true
    permalink: /:collection/:path/

google_analytics:
  tracking_id: UA-80515457-1
  anonymize_ip: true

include:
  - _pages

#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

disqus:
  shortname: usnewson

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
